name: 什么值得买签到

on:
  #  push:
  #    branches: [ main ]
  schedule:
    - cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install
        run: npm install
      - name: Run app
        run: node smzdm.js
        env:
          SMZDM_COOKIE: ${{ secrets.SMZDM_COOKIE }}
          SCKEY: ${{ secrets.SCKEY }}
